# Generated by Django 2.2.1 on 2019-06-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(default='unread', max_length=10)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(max_length=2000)),
                ('expirationTime', models.DateTimeField(null=True)),
                ('keys', models.TextField(max_length=2000)),
                ('user_id', models.IntegerField()),
                ('device', models.CharField(max_length=512)),
            ],
        ),
    ]
