# Generated by Django 2.2.1 on 2019-06-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotificationapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushNotification',
        ),
    ]
