# Generated by Django 2.2.1 on 2019-07-23 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotificationapp', '0002_delete_pushnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='keys',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
