# Generated by Django 2.2.1 on 2019-07-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotificationapp', '0003_auto_20190723_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='user_id',
            new_name='user',
        ),
    ]
