# Generated by Django 2.2.1 on 2019-05-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_resetpassword_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='components',
            name='flat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='components',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
