# Generated by Django 2.2.1 on 2019-05-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20190514_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='building',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='flat',
            field=models.BooleanField(default=True),
        ),
    ]
