# Generated by Django 2.2.1 on 2019-05-15 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20190514_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingplans',
            name='plan_file',
            field=models.FileField(null=True, upload_to='static/assets/building/plan_pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='flatplans',
            name='plan_file',
            field=models.FileField(null=True, upload_to='static/assets/flat/plan_pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.FileField(null=True, upload_to='static/assets/avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg'])]),
        ),
    ]
