# Generated by Django 2.2.1 on 2019-05-15 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_auto_20190515_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.FileField(null=True, upload_to='adminapp/static/assets/avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg'])]),
        ),
    ]
