# Generated by Django 2.2.1 on 2019-05-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_auto_20190515_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handworker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='handworker',
            name='email',
        ),
    ]
