# Generated by Django 2.2.1 on 2019-05-16 09:09

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20190516_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handworker',
            name='working_type',
            field=django_mysql.models.JSONField(default='[]'),
        ),
    ]
