# Generated by Django 2.2.1 on 2019-05-20 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_auto_20190520_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='assigned_by',
        ),
        migrations.AddField(
            model_name='buildingcomponents',
            name='assign_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_assign_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildingcomponents',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
