# Generated by Django 2.2.1 on 2019-05-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_auto_20190521_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='number',
        ),
        migrations.AddField(
            model_name='buildings',
            name='aussenwande_eg_og_dg',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildings',
            name='dach',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildings',
            name='display_number',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildings',
            name='fenster_beschattung',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildings',
            name='grundung',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildings',
            name='hause_number',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
