# Generated by Django 2.2.1 on 2019-05-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_auto_20190521_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='dach',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='flats',
            name='client_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
