# Generated by Django 2.2.1 on 2019-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_auto_20190522_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='unique_key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
