# Generated by Django 2.2.1 on 2019-05-23 07:47

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_auto_20190522_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=adminapp.models.TaskStatusType(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='to_do', max_length=20),
        ),
    ]
