# Generated by Django 2.2.1 on 2019-05-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_auto_20190523_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingplans',
            name='plan_file',
            field=models.FileField(null=True, upload_to='adminapp/static/assets/building/plans/'),
        ),
        migrations.AlterField(
            model_name='flatplans',
            name='plan_file',
            field=models.FileField(null=True, upload_to='adminapp/static/assets/flat/plans/'),
        ),
        migrations.AlterField(
            model_name='projectplans',
            name='plan_file',
            field=models.FileField(null=True, upload_to='adminapp/static/assets/project/plans/'),
        ),
    ]
