# Generated by Django 2.2.1 on 2019-05-24 04:23

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_auto_20190523_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='assets/avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg'])]),
        ),
    ]
