# Generated by Django 2.2.1 on 2019-05-24 04:36

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_auto_20190524_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingplans',
            name='plan_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='building/plans/'),
        ),
        migrations.AlterField(
            model_name='flatplans',
            name='plan_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='flat/plans/'),
        ),
        migrations.AlterField(
            model_name='projectplans',
            name='plan_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='project/plans/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg', 'jpeg'])]),
        ),
    ]
