# Generated by Django 2.2.1 on 2019-05-28 04:18

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_auto_20190524_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='current_activity',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
