# Generated by Django 2.2.1 on 2019-05-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_auto_20190528_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='number',
            field=models.CharField(max_length=45),
        ),
    ]
