# Generated by Django 2.2.1 on 2019-06-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_auto_20190529_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handworker',
            old_name='telephone',
            new_name='telephone_mobile',
        ),
        migrations.AddField(
            model_name='handworker',
            name='telephone_office',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
