# Generated by Django 2.2.1 on 2019-06-14 10:29

import adminapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_auto_20190611_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=adminapp.models.NotificationType(choices=[('edit_task', 'Edit Task'), ('assign_worker', 'Assign Worker'), ('change_task_status', 'Change Task Status'), ('task_comment', 'Task Comment'), ('attach_file', 'Attach File'), ('change_due_date', 'Change Due Date')], max_length=20),
        ),
    ]
