# Generated by Django 2.2.1 on 2019-06-15 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_auto_20190614_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstatus',
            name='sending_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
