# Generated by Django 2.2.1 on 2019-06-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_notificationstatus_sending_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstatus',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
